name: instabug_flutter
version: 9.1.7
description: >-
  Instabug is an in-app feedback and bug reporting tool for mobile apps. 
  With just a simple shake, your users or beta testers can report bugs or 
  send in-app feedback and the SDK will capture an environment snapshot of 
  your user's device including all console logs, server-side network requests 
  and bug reproduction steps compiling all these details in one organised dashboard
  to help you debug and fix bugs faster.
author: Instabug <support@instabug.com>
homepage: https://github.com/Instabug/Instabug-Flutter#readme
documentation: https://github.com/Instabug/Instabug-Flutter#readme

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stack_trace:  ^1.9.3
  meta: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

flutter:
  plugin:
    androidPackage: com.instabug.instabugflutter
    pluginClass: InstabugFlutterPlugin
