name: instabug_flutter
version: 16.0.1
description: >-
  Instabug empowers mobile teams to monitor, prioritize, and debug
  performance and stability issues throughout the app development lifecycle.
homepage: https://www.instabug.com/platforms/flutter
repository: https://github.com/Instabug/Instabug-Flutter
documentation: https://docs.instabug.com/docs/flutter-overview

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  stack_trace: ^1.10.0

dev_dependencies:
  build_runner: ^2.0.3
  fake_async: ">=1.2.0 <1.4.0"
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  # mockito v5.2.0 is needed for running Flutter 2 tests on CI
  mockito: ">=5.2.0 <5.5.0"
  pana: ^0.21.0
  # pigeon v3.0.0 is needed for running Flutter 2 tests on CI
  pigeon: ">=3.0.0 <=10.1.5"

flutter:
  plugin:
    platforms:
      android:
        package: com.instabug.flutter
        pluginClass: InstabugFlutterPlugin
      ios:
        pluginClass: InstabugFlutterPlugin

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=1.17.0"
