name: instabug_flutter_modular
description: An add-on for the Instabug Flutter SDK that provides screen loading support for Flutter Modular v5.
version: 1.0.0
homepage: https://www.instabug.com
repository: https://github.com/Instabug/Instabug-Flutter/tree/refactor/monorepo/packages/instabug_flutter_modular

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: '>=5.0.0 <6.0.0'
  instabug_flutter: '>=13.2.0 <14.0.0'
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # mockito v5.2.0 is needed for running Flutter 2 tests on CI
  mockito: '>=5.2.0 <=5.4.4'
  # A specific version isn't specified as we want to use the version used in flutter_modular
  modular_core:
  pana: ^0.21.0
