name: instabug_http_client
description:
  This package is an add on to instabug_flutter. It intercepts any requests performed
  with http Package and sends them to the report that will be sent to the dashboard.
version: 2.7.0
homepage: https://github.com/Instabug/Instabug-Flutter#readme
documentation: https://docs.instabug.com/docs/flutter-overview
repository: https://github.com/Instabug/Instabug-Flutter/tree/master/packages/instabug_http_client

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ">=0.13.0 <2.0.0"
  instabug_flutter: ">=14.0.0 <17.0.0"
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
  pana: ^0.21.0
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
